version: '3.7'

volumes:
  nexus-data:
    external:
      name: nexus-data
services:
  nexus:
    image: sonatype/nexus3:3.16.2
    container_name: nexus-3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
